package Findzzer.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Api = 0;
  public static final int Array = 1;
  public static final int Button = 2;
  public static final int Chart = 3;
  public static final int ClicakbleText = 4;
  public static final int Components = 5;
  public static final int DataTable = 6;
  public static final int Dialog = 7;
  public static final int Dropdown = 8;
  public static final int Findzzer = 9;
  public static final int Footer = 10;
  public static final int Form = 11;
  public static final int Header = 12;
  public static final int Menu = 13;
  public static final int SearchBar = 14;
  public static final int Settings = 15;
  public static final int SocialMedia = 16;
  public static final int Theme = 17;
  public static final int View = 18;
  public static final int chartObject = 19;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL);
    builder.put(0x34a67cda660d35b1L, Api);
    builder.put(0x750a0f6baa98f026L, Array);
    builder.put(0x34a67cda660d35fdL, Button);
    builder.put(0x34a67cda660d35cfL, Chart);
    builder.put(0x34a67cda660d35f7L, ClicakbleText);
    builder.put(0x34a67cda660d35b6L, Components);
    builder.put(0x34a67cda660d35dfL, DataTable);
    builder.put(0x34a67cda660d3603L, Dialog);
    builder.put(0x34a67cda660d35e8L, Dropdown);
    builder.put(0x6d40fd6461735b05L, Findzzer);
    builder.put(0x34a67cda660d361eL, Footer);
    builder.put(0x34a67cda660d35eeL, Form);
    builder.put(0x34a67cda660d3617L, Header);
    builder.put(0x34a67cda660d3609L, Menu);
    builder.put(0x34a67cda660d3610L, SearchBar);
    builder.put(0x34a67cda660d35aeL, Settings);
    builder.put(0x34a67cda660d362fL, SocialMedia);
    builder.put(0x34a67cda660d3626L, Theme);
    builder.put(0x34a67cda660d35a8L, View);
    builder.put(0x750a0f6baa9ca412L, chartObject);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
