package Findzzer.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptApi = createDescriptorForApi();
  /*package*/ final ConceptDescriptor myConceptArray = createDescriptorForArray();
  /*package*/ final ConceptDescriptor myConceptButton = createDescriptorForButton();
  /*package*/ final ConceptDescriptor myConceptCard = createDescriptorForCard();
  /*package*/ final ConceptDescriptor myConceptChart = createDescriptorForChart();
  /*package*/ final ConceptDescriptor myConceptClicakbleText = createDescriptorForClicakbleText();
  /*package*/ final ConceptDescriptor myConceptComponents = createDescriptorForComponents();
  /*package*/ final ConceptDescriptor myConceptDataTable = createDescriptorForDataTable();
  /*package*/ final ConceptDescriptor myConceptDropdown = createDescriptorForDropdown();
  /*package*/ final ConceptDescriptor myConceptFindzzer = createDescriptorForFindzzer();
  /*package*/ final ConceptDescriptor myConceptFooter = createDescriptorForFooter();
  /*package*/ final ConceptDescriptor myConceptForm = createDescriptorForForm();
  /*package*/ final ConceptDescriptor myConceptHeader = createDescriptorForHeader();
  /*package*/ final ConceptDescriptor myConceptMenu = createDescriptorForMenu();
  /*package*/ final ConceptDescriptor myConceptSearchBar = createDescriptorForSearchBar();
  /*package*/ final ConceptDescriptor myConceptSettings = createDescriptorForSettings();
  /*package*/ final ConceptDescriptor myConceptSocialMedia = createDescriptorForSocialMedia();
  /*package*/ final ConceptDescriptor myConceptTheme = createDescriptorForTheme();
  /*package*/ final ConceptDescriptor myConceptView = createDescriptorForView();
  /*package*/ final ConceptDescriptor myConceptchartObject = createDescriptorForchartObject();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptApi, myConceptArray, myConceptButton, myConceptCard, myConceptChart, myConceptClicakbleText, myConceptComponents, myConceptDataTable, myConceptDropdown, myConceptFindzzer, myConceptFooter, myConceptForm, myConceptHeader, myConceptMenu, myConceptSearchBar, myConceptSettings, myConceptSocialMedia, myConceptTheme, myConceptView, myConceptchartObject);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Api:
        return myConceptApi;
      case LanguageConceptSwitch.Array:
        return myConceptArray;
      case LanguageConceptSwitch.Button:
        return myConceptButton;
      case LanguageConceptSwitch.Card:
        return myConceptCard;
      case LanguageConceptSwitch.Chart:
        return myConceptChart;
      case LanguageConceptSwitch.ClicakbleText:
        return myConceptClicakbleText;
      case LanguageConceptSwitch.Components:
        return myConceptComponents;
      case LanguageConceptSwitch.DataTable:
        return myConceptDataTable;
      case LanguageConceptSwitch.Dropdown:
        return myConceptDropdown;
      case LanguageConceptSwitch.Findzzer:
        return myConceptFindzzer;
      case LanguageConceptSwitch.Footer:
        return myConceptFooter;
      case LanguageConceptSwitch.Form:
        return myConceptForm;
      case LanguageConceptSwitch.Header:
        return myConceptHeader;
      case LanguageConceptSwitch.Menu:
        return myConceptMenu;
      case LanguageConceptSwitch.SearchBar:
        return myConceptSearchBar;
      case LanguageConceptSwitch.Settings:
        return myConceptSettings;
      case LanguageConceptSwitch.SocialMedia:
        return myConceptSocialMedia;
      case LanguageConceptSwitch.Theme:
        return myConceptTheme;
      case LanguageConceptSwitch.View:
        return myConceptView;
      case LanguageConceptSwitch.chartObject:
        return myConceptchartObject;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForApi() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Api", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b1L);
    b.class_(false, false, false);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078065");
    b.version(3);
    b.property("baseUrl", 0x34a67cda660e93ceL).type(PrimitiveTypeId.STRING).origin("3793857013563167694").done();
    b.property("apis", 0x34a67cda660e93cfL).type(PrimitiveTypeId.STRING).origin("3793857013563167695").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForArray() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Array", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x750a0f6baa98f026L);
    b.class_(false, false, false);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/8433570207302742054");
    b.version(3);
    b.aggregate("objectArray", 0x750a0f6baa98f028L).target(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL).optional(true).ordered(true).multiple(true).origin("8433570207302742056").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForButton() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Button", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35fdL);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078141");
    b.version(3);
    b.property("label", 0x34a67cda660d35ffL).type(PrimitiveTypeId.STRING).origin("3793857013563078143").done();
    b.property("action", 0x34a67cda660d3600L).type(PrimitiveTypeId.STRING).origin("3793857013563078144").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Card", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3603L);
    b.class_(false, false, false);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078147");
    b.version(3);
    b.property("message", 0x34a67cda660d3605L).type(PrimitiveTypeId.STRING).origin("3793857013563078149").done();
    b.property("action", 0x34a67cda660d3607L).type(PrimitiveTypeId.BOOLEAN).origin("3793857013563078151").done();
    b.property("title", 0x3ce6b4aea251ece9L).type(PrimitiveTypeId.STRING).origin("4388393549059714281").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForChart() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Chart", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35cfL);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078095");
    b.version(3);
    b.property("type", 0x2d192c49a56284edL).type(PrimitiveTypeId.STRING).origin("3249677300943455469").done();
    b.property("action", 0x2d192c49a56284eeL).type(PrimitiveTypeId.INTEGER).origin("3249677300943455470").done();
    b.aggregate("data", 0x750a0f6baa98f035L).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x750a0f6baa9ca412L).optional(true).ordered(true).multiple(true).origin("8433570207302742069").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClicakbleText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "ClicakbleText", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35f7L);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078135");
    b.version(3);
    b.property("clickableWords", 0x34a67cda660d35f9L).type(PrimitiveTypeId.STRING).origin("3793857013563078137").done();
    b.property("text", 0x34a67cda660d35faL).type(PrimitiveTypeId.STRING).origin("3793857013563078138").done();
    b.property("action", 0x34a67cda660d35fbL).type(PrimitiveTypeId.STRING).origin("3793857013563078139").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComponents() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Components", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078070");
    b.version(3);
    b.aggregate("DataTable", 0x504507f2c966603dL).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35dfL).optional(true).ordered(true).multiple(true).origin("5784038035769679933").done();
    b.aggregate("Card", 0x3ce6b4aea251ed10L).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3603L).optional(true).ordered(true).multiple(true).origin("4388393549059714320").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataTable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "DataTable", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35dfL);
    b.class_(false, false, false);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078111");
    b.version(3);
    b.property("headers", 0x34a67cda660d35e4L).type(PrimitiveTypeId.STRING).origin("3793857013563078116").done();
    b.property("action", 0x34a67cda660d35e5L).type(PrimitiveTypeId.STRING).origin("3793857013563078117").done();
    b.property("data", 0x34a67cda660d35e6L).type(PrimitiveTypeId.STRING).origin("3793857013563078118").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDropdown() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Dropdown", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35e8L);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078120");
    b.version(3);
    b.property("label", 0x34a67cda660d35eaL).type(PrimitiveTypeId.STRING).origin("3793857013563078122").done();
    b.property("options", 0x34a67cda660d35ecL).type(PrimitiveTypeId.STRING).origin("3793857013563078124").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFindzzer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Findzzer", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x6d40fd6461735b05L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/7872570756217133829");
    b.version(3);
    b.property("dsl_name", 0x5b76049df638caebL).type(PrimitiveTypeId.STRING).origin("6590460181190593259").done();
    b.aggregate("page", 0x34a67cda660d355aL).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35a8L).optional(true).ordered(true).multiple(true).origin("3793857013563077978").done();
    b.aggregate("settings", 0x34a67cda660d355bL).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35aeL).optional(true).ordered(true).multiple(false).origin("3793857013563077979").done();
    b.aggregate("api", 0x34a67cda660d355dL).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b1L).optional(true).ordered(true).multiple(false).origin("3793857013563077981").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFooter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Footer", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d361eL);
    b.class_(false, false, false);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078174");
    b.version(3);
    b.property("links", 0x34a67cda660d3621L).type(PrimitiveTypeId.STRING).origin("3793857013563078177").done();
    b.property("copyRight", 0x34a67cda660d3622L).type(PrimitiveTypeId.STRING).origin("3793857013563078178").done();
    b.aggregate("SocilaMedia", 0x34a67cda660d3623L).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d362fL).optional(true).ordered(true).multiple(true).origin("3793857013563078179").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForForm() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Form", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35eeL);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078126");
    b.version(3);
    b.property("fields", 0x34a67cda660d35f3L).type(PrimitiveTypeId.STRING).origin("3793857013563078131").done();
    b.property("action", 0x34a67cda660d35f4L).type(PrimitiveTypeId.STRING).origin("3793857013563078132").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHeader() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Header", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3617L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078167");
    b.version(3);
    b.property("logo", 0x34a67cda660d361bL).type(PrimitiveTypeId.STRING).origin("3793857013563078171").done();
    b.property("title", 0x34a67cda660d361cL).type(PrimitiveTypeId.STRING).origin("3793857013563078172").done();
    b.property("options", 0x34a67cda660d361dL).type(PrimitiveTypeId.STRING).origin("3793857013563078173").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenu() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Menu", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3609L);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078153");
    b.version(3);
    b.property("action", 0x34a67cda660d360dL).type(PrimitiveTypeId.STRING).origin("3793857013563078157").done();
    b.property("items", 0x34a67cda660d360eL).type(PrimitiveTypeId.STRING).origin("3793857013563078158").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSearchBar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "SearchBar", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3610L);
    b.class_(false, false, false);
    // extends: Findzzer.structure.Components
    b.super_(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078160");
    b.version(3);
    b.property("placeholder", 0x34a67cda660d3614L).type(PrimitiveTypeId.STRING).origin("3793857013563078164").done();
    b.property("displayField", 0x34a67cda660d3615L).type(PrimitiveTypeId.STRING).origin("3793857013563078165").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSettings() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Settings", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35aeL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078062");
    b.version(3);
    b.property("navigationMenu", 0x34a67cda66100068L).type(PrimitiveTypeId.BOOLEAN).origin("3793857013563261032").done();
    b.aggregate("header", 0x34a67cda66100064L).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3617L).optional(false).ordered(true).multiple(false).origin("3793857013563261028").done();
    b.aggregate("footer", 0x34a67cda66100065L).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d361eL).optional(false).ordered(true).multiple(false).origin("3793857013563261029").done();
    b.aggregate("theme", 0x34a67cda66100066L).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3626L).optional(false).ordered(true).multiple(false).origin("3793857013563261030").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSocialMedia() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "SocialMedia", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d362fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078191");
    b.version(3);
    b.property("facebook", 0x34a67cda660d3631L).type(PrimitiveTypeId.STRING).origin("3793857013563078193").done();
    b.property("instagram", 0x34a67cda660d3632L).type(PrimitiveTypeId.STRING).origin("3793857013563078194").done();
    b.property("twitter", 0x34a67cda660d3633L).type(PrimitiveTypeId.STRING).origin("3793857013563078195").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTheme() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "Theme", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3626L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078182");
    b.version(3);
    b.property("font", 0x34a67cda660d3628L).type(PrimitiveTypeId.STRING).origin("3793857013563078184").done();
    b.property("mode", 0x34a67cda660d3629L).type(PrimitiveTypeId.STRING).origin("3793857013563078185").done();
    b.property("accentColor", 0x34a67cda660d362aL).type(PrimitiveTypeId.STRING).origin("3793857013563078186").done();
    b.property("secondaryColor", 0x34a67cda660d362bL).type(PrimitiveTypeId.STRING).origin("3793857013563078187").done();
    b.property("primaryColor", 0x34a67cda660d362cL).type(PrimitiveTypeId.STRING).origin("3793857013563078188").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForView() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "View", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35a8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/3793857013563078056");
    b.version(3);
    b.property("version", 0x34a67cda660d35acL).type(PrimitiveTypeId.INTEGER).origin("3793857013563078060").done();
    b.aggregate("Component", 0x504507f2c95684eaL).target(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35b6L).optional(true).ordered(true).multiple(true).origin("5784038035768640746").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForchartObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Findzzer", "chartObject", 0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x750a0f6baa9ca412L);
    b.class_(false, false, false);
    b.origin("r:881a2812-7fae-40ca-93b0-e623549d2ace(Findzzer.structure)/8433570207302984722");
    b.version(3);
    b.property("xValue", 0x750a0f6baa9ca419L).type(PrimitiveTypeId.INTEGER).origin("8433570207302984729").done();
    b.property("yValue", 0x750a0f6baa9ca41bL).type(PrimitiveTypeId.INTEGER).origin("8433570207302984731").done();
    b.property("label", 0x750a0f6baa9ca41cL).type(PrimitiveTypeId.INTEGER).origin("8433570207302984732").done();
    return b.create();
  }
}
