package Findzzer.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Card_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("============================================CARD===============================================================");

    tgs.append("\n \n <template>\n  <v-card>\n");
    tgs.append("<h1>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.title$neCU));
    tgs.append("</h1>");
    tgs.append("<p>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.message$GJVy));
    tgs.append("</p>");

    tgs.append("  <v-card-title>Name: {{ item.name }}</v-card-title>\n    <v-card-subtitle>Color: {{ item.color }}</v-card-subtitle>\n    <v-card-actions>\n      <v-icon class=\"me-2\" size=\"small\" @click=\"editItem(item)\">\n        mdi-pencil\n      </v-icon>\n      <v-icon size=\"small\" @click=\"deleteItem(item)\"> mdi-delete </v-icon>\n    </v-card-actions>\n  </v-card>\n</template>");
    tgs.append("===========================================================================================================");

  }

  private static final class PROPS {
    /*package*/ static final SProperty title$neCU = MetaAdapterFactory.getProperty(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3603L, 0x3ce6b4aea251ece9L, "title");
    /*package*/ static final SProperty message$GJVy = MetaAdapterFactory.getProperty(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d3603L, 0x34a67cda660d3605L, "message");
  }
}
