package Findzzer.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DataTable_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<template>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<v-data-table :headers=\"headers\"\n      :items=\"items\"\n      :items-per-page=\"5\"\n      class=\"elevation-1\"\n    >");
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<template v-slot:top>");
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<v-toolbar flat>");
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<v-toolbar-title>{{ title }}</v-toolbar-title>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.headers$GoE5));
    tgs.append("<v-spacer>\"</v-spacer>");
    tgs.append("  <v-btn color=\"primary\" dark @click=\"$emit('add-item')\">\n            New Item\n          </v-btn>");
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</v-toolbar>");
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</template>");
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</data-table>");
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</template>");
  }

  private static final class PROPS {
    /*package*/ static final SProperty headers$GoE5 = MetaAdapterFactory.getProperty(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35dfL, 0x34a67cda660d35e4L, "headers");
  }
}
