package Findzzer.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DataTable_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("=======================DATA TABLE====================================================================================");
    tgs.newLine();

    tgs.append("<template>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<h1>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.headers$GoE5));
    tgs.append("</h1>");

    tgs.append("<v-data-table :headers=\"headers\"\n      :items=\"items\"\n      :items-per-page=\"5\"\n      class=\"elevation-1\"\n    >\n");

    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<template v-slot:top>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<v-toolbar flat>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<v-toolbar-title>{{ title }}</v-toolbar-title>");
    tgs.newLine();
    tgs.append("  <v-btn color=\"primary\" dark @click=\"$emit('add-item')\">\n New Item\n </v-btn>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</v-toolbar>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</template>");
    tgs.newLine();
    tgs.append("<template v-slot:[`item.actions`]=\"{ item }\">\n        <v-icon class=\"me-2\" size=\"small\" @click=\"$emit('edit-item', item)\">\n          mdi-pencil\n        </v-icon>\n        <v-icon size=\"small\" @click=\"$emit('delete-item', item)\">\n          mdi-delete\n        </v-icon>\n      </template>\n    ");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</v-data-table>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("</template>");
    tgs.newLine();
    tgs.append("===========================================================================================================");

  }

  private static final class PROPS {
    /*package*/ static final SProperty headers$GoE5 = MetaAdapterFactory.getProperty(0xf4fcfb4c57c745ceL, 0xa8ab88347bde635aL, 0x34a67cda660d35dfL, 0x34a67cda660d35e4L, "headers");
  }
}
