package Findzzer.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;

public class Footer_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("=======================FOOTER============================================");
    tgs.newLine();

    tgs.append("<template>\n  <v-footer color=\"grey darken-4\" padless>\n    <v-container class=\"text-center py-4\">\n      <p class=\"white--text\">&copy; 2024 UniqueApp. All rights reserved.</p>\n      <p class=\"white--text\">\n        Email:\n        <a\n          href=\"mailto:support@uniqueapp.com\"\n          class=\"white--text\"\n          aria-label=\"Email support\"\n        >\n          support@uniqueapp.com\n        </a>\n      </p>\n    </v-container>\n  </v-footer>\n</template>\n");
  }
}
